# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bebee7d60d2fed2c515d53f742e66f69d5034ed642dd122e9956b2f052520518e47c0fa5bd1ba78e2d46421b094f9048aec729e80e230b1147a381946b1b5ec

test:
  secret_key_base: e15674a53b009ba747e98ad719080d8ac6a0610757d50027dd3efb2b0d81c4e2d66761b8bdf3410c862eb2abc4be67c684a0de482fbb47501a0322d68481a533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
